# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventana1.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QColumnView, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QWidget)
from . import img_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(974, 484)
        MainWindow.setAutoFillBackground(False)
        self.actionNuevo = QAction(MainWindow)
        self.actionNuevo.setObjectName(u"actionNuevo")
        icon = QIcon()
        icon.addFile(u":/images/icons/new.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNuevo.setIcon(icon)
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        icon1 = QIcon()
        icon1.addFile(u":/images/icons/save.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGuardar.setIcon(icon1)
        self.actionGuardar_Como = QAction(MainWindow)
        self.actionGuardar_Como.setObjectName(u"actionGuardar_Como")
        icon2 = QIcon()
        icon2.addFile(u":/images/icons/save_as.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGuardar_Como.setIcon(icon2)
        self.actionSobre_Nosotros = QAction(MainWindow)
        self.actionSobre_Nosotros.setObjectName(u"actionSobre_Nosotros")
        icon3 = QIcon()
        icon3.addFile(u":/images/icons/info.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSobre_Nosotros.setIcon(icon3)
        self.actionSobre_Nosotros.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        icon4 = QIcon()
        icon4.addFile(u":/images/icons/open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbrir.setIcon(icon4)
        self.actionCerrar = QAction(MainWindow)
        self.actionCerrar.setObjectName(u"actionCerrar")
        icon5 = QIcon()
        icon5.addFile(u":/images/icons/close.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCerrar.setIcon(icon5)
        self.actionSalir = QAction(MainWindow)
        self.actionSalir.setObjectName(u"actionSalir")
        icon6 = QIcon()
        icon6.addFile(u":/images/icons/exit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSalir.setIcon(icon6)
        self.actionConfiguracion = QAction(MainWindow)
        self.actionConfiguracion.setObjectName(u"actionConfiguracion")
        icon7 = QIcon()
        icon7.addFile(u":/images/icons/settings.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionConfiguracion.setIcon(icon7)
        self.actionExportar = QAction(MainWindow)
        self.actionExportar.setObjectName(u"actionExportar")
        icon8 = QIcon()
        icon8.addFile(u":/images/icons/export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExportar.setIcon(icon8)
        self.actionImprimir = QAction(MainWindow)
        self.actionImprimir.setObjectName(u"actionImprimir")
        icon9 = QIcon()
        icon9.addFile(u":/images/icons/print.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImprimir.setIcon(icon9)
        self.actionRecientes = QAction(MainWindow)
        self.actionRecientes.setObjectName(u"actionRecientes")
        icon10 = QIcon()
        icon10.addFile(u":/images/icons/recent.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRecientes.setIcon(icon10)
        self.actionCopiar = QAction(MainWindow)
        self.actionCopiar.setObjectName(u"actionCopiar")
        icon11 = QIcon()
        if QIcon.hasThemeIcon(QIcon.ThemeIcon.EditCopy):
            icon11 = QIcon.fromTheme(QIcon.ThemeIcon.EditCopy)
        else:
            icon11.addFile(u":/images/icons/copy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.actionCopiar.setIcon(icon11)
        self.actionPegar = QAction(MainWindow)
        self.actionPegar.setObjectName(u"actionPegar")
        icon12 = QIcon()
        icon12.addFile(u":/images/icons/paste.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPegar.setIcon(icon12)
        self.actionCortar = QAction(MainWindow)
        self.actionCortar.setObjectName(u"actionCortar")
        icon13 = QIcon()
        icon13.addFile(u":/images/icons/cut.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCortar.setIcon(icon13)
        self.actionTutorial = QAction(MainWindow)
        self.actionTutorial.setObjectName(u"actionTutorial")
        icon14 = QIcon()
        icon14.addFile(u":/images/icons/help.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTutorial.setIcon(icon14)
        self.actionSobre_Nosotros_2 = QAction(MainWindow)
        self.actionSobre_Nosotros_2.setObjectName(u"actionSobre_Nosotros_2")
        self.actionSobre_Nosotros_2.setIcon(icon3)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.columnView = QColumnView(self.centralwidget)
        self.columnView.setObjectName(u"columnView")
        self.columnView.setGeometry(QRect(0, 0, 971, 461))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 974, 22))
        self.menubar.setAutoFillBackground(False)
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menuEditar = QMenu(self.menubar)
        self.menuEditar.setObjectName(u"menuEditar")
        self.menuAyuda = QMenu(self.menubar)
        self.menuAyuda.setObjectName(u"menuAyuda")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionRecientes)
        self.menuArchivo.addAction(self.actionCerrar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExportar)
        self.menuArchivo.addAction(self.actionImprimir)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSobre_Nosotros)
        self.menuArchivo.addAction(self.actionConfiguracion)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addAction(self.actionCortar)
        self.menuAyuda.addAction(self.actionTutorial)
        self.menuAyuda.addAction(self.actionSobre_Nosotros_2)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNuevo.setText(QCoreApplication.translate("MainWindow", u"Nuevo", None))
#if QT_CONFIG(shortcut)
        self.actionNuevo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar_Como.setText(QCoreApplication.translate("MainWindow", u"Guardar Como", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar_Como.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSobre_Nosotros.setText(QCoreApplication.translate("MainWindow", u"Sobre Nosotros", None))
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionCerrar.setText(QCoreApplication.translate("MainWindow", u"Cerrar", None))
        self.actionSalir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.actionConfiguracion.setText(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n", None))
        self.actionExportar.setText(QCoreApplication.translate("MainWindow", u"Exportar", None))
        self.actionImprimir.setText(QCoreApplication.translate("MainWindow", u"Imprimir", None))
#if QT_CONFIG(shortcut)
        self.actionImprimir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionRecientes.setText(QCoreApplication.translate("MainWindow", u"Recientes", None))
        self.actionCopiar.setText(QCoreApplication.translate("MainWindow", u"Copiar", None))
#if QT_CONFIG(shortcut)
        self.actionCopiar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPegar.setText(QCoreApplication.translate("MainWindow", u"Pegar", None))
#if QT_CONFIG(shortcut)
        self.actionPegar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionCortar.setText(QCoreApplication.translate("MainWindow", u"Cortar", None))
#if QT_CONFIG(shortcut)
        self.actionCortar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionTutorial.setText(QCoreApplication.translate("MainWindow", u"Tutorial", None))
        self.actionSobre_Nosotros_2.setText(QCoreApplication.translate("MainWindow", u"Sobre Nosotros", None))
#if QT_CONFIG(shortcut)
        self.actionSobre_Nosotros_2.setShortcut(QCoreApplication.translate("MainWindow", u"F12", None))
#endif // QT_CONFIG(shortcut)
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
        self.menuEditar.setTitle(QCoreApplication.translate("MainWindow", u"Editar", None))
        self.menuAyuda.setTitle(QCoreApplication.translate("MainWindow", u"Ayuda", None))
    # retranslateUi

