# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventana1.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QSplitter, QWidget)

from board_view import BoardView
from . import img_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(974, 484)
        MainWindow.setAutoFillBackground(False)
        self.actionNuevo = QAction(MainWindow)
        self.actionNuevo.setObjectName(u"actionNuevo")
        icon = QIcon()
        icon.addFile(u":/images/icons/new.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNuevo.setIcon(icon)
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        icon1 = QIcon()
        icon1.addFile(u":/images/icons/save.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGuardar.setIcon(icon1)
        self.actionGuardar_Como = QAction(MainWindow)
        self.actionGuardar_Como.setObjectName(u"actionGuardar_Como")
        icon2 = QIcon()
        icon2.addFile(u":/images/icons/save_as.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGuardar_Como.setIcon(icon2)
        self.actionSobre_Nosotros = QAction(MainWindow)
        self.actionSobre_Nosotros.setObjectName(u"actionSobre_Nosotros")
        icon3 = QIcon()
        icon3.addFile(u":/images/icons/info.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSobre_Nosotros.setIcon(icon3)
        self.actionSobre_Nosotros.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        icon4 = QIcon()
        icon4.addFile(u":/images/icons/open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbrir.setIcon(icon4)
        self.actionCerrar = QAction(MainWindow)
        self.actionCerrar.setObjectName(u"actionCerrar")
        icon5 = QIcon()
        icon5.addFile(u":/images/icons/close.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCerrar.setIcon(icon5)
        self.actionSalir = QAction(MainWindow)
        self.actionSalir.setObjectName(u"actionSalir")
        icon6 = QIcon()
        icon6.addFile(u":/images/icons/exit.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSalir.setIcon(icon6)
        self.actionConfiguracion = QAction(MainWindow)
        self.actionConfiguracion.setObjectName(u"actionConfiguracion")
        icon7 = QIcon()
        icon7.addFile(u":/images/icons/settings.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionConfiguracion.setIcon(icon7)
        self.actionExportar = QAction(MainWindow)
        self.actionExportar.setObjectName(u"actionExportar")
        icon8 = QIcon()
        icon8.addFile(u":/images/icons/export.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExportar.setIcon(icon8)
        self.actionImprimir = QAction(MainWindow)
        self.actionImprimir.setObjectName(u"actionImprimir")
        icon9 = QIcon()
        icon9.addFile(u":/images/icons/print.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImprimir.setIcon(icon9)
        self.actionRecientes = QAction(MainWindow)
        self.actionRecientes.setObjectName(u"actionRecientes")
        icon10 = QIcon()
        icon10.addFile(u":/images/icons/recent.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRecientes.setIcon(icon10)
        self.actionCopiar = QAction(MainWindow)
        self.actionCopiar.setObjectName(u"actionCopiar")
        icon11 = QIcon()
        if QIcon.hasThemeIcon(QIcon.ThemeIcon.EditCopy):
            icon11 = QIcon.fromTheme(QIcon.ThemeIcon.EditCopy)
        else:
            icon11.addFile(u":/images/icons/copy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.actionCopiar.setIcon(icon11)
        self.actionPegar = QAction(MainWindow)
        self.actionPegar.setObjectName(u"actionPegar")
        icon12 = QIcon()
        icon12.addFile(u":/images/icons/paste.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPegar.setIcon(icon12)
        self.actionCortar = QAction(MainWindow)
        self.actionCortar.setObjectName(u"actionCortar")
        icon13 = QIcon()
        icon13.addFile(u":/images/icons/cut.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCortar.setIcon(icon13)
        self.actionTutorial = QAction(MainWindow)
        self.actionTutorial.setObjectName(u"actionTutorial")
        icon14 = QIcon()
        icon14.addFile(u":/images/icons/help.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionTutorial.setIcon(icon14)
        self.actionSobre_Nosotros_2 = QAction(MainWindow)
        self.actionSobre_Nosotros_2.setObjectName(u"actionSobre_Nosotros_2")
        self.actionSobre_Nosotros_2.setIcon(icon3)
        self.actionCargar_Tema = QAction(MainWindow)
        self.actionCargar_Tema.setObjectName(u"actionCargar_Tema")
        icon15 = QIcon()
        icon15.addFile(u":/images/icons/theme.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCargar_Tema.setIcon(icon15)
        self.actionResetear_Tema = QAction(MainWindow)
        self.actionResetear_Tema.setObjectName(u"actionResetear_Tema")
        icon16 = QIcon()
        icon16.addFile(u":/images/icons/reset.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionResetear_Tema.setIcon(icon16)
        self.actionCargar_UI = QAction(MainWindow)
        self.actionCargar_UI.setObjectName(u"actionCargar_UI")
        icon17 = QIcon()
        icon17.addFile(u":/images/icons/UI.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCargar_UI.setIcon(icon17)
        self.actionResetear_UI = QAction(MainWindow)
        self.actionResetear_UI.setObjectName(u"actionResetear_UI")
        self.actionResetear_UI.setIcon(icon16)
        self.actionCargar_CI = QAction(MainWindow)
        self.actionCargar_CI.setObjectName(u"actionCargar_CI")
        icon18 = QIcon()
        icon18.addFile(u":/images/icons/IC.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCargar_CI.setIcon(icon18)
        self.actionGuardar_CI = QAction(MainWindow)
        self.actionGuardar_CI.setObjectName(u"actionGuardar_CI")
        icon19 = QIcon()
        icon19.addFile(u":/images/icons/Create_IC.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionGuardar_CI.setIcon(icon19)
        self.actionCrear_Seccion = QAction(MainWindow)
        self.actionCrear_Seccion.setObjectName(u"actionCrear_Seccion")
        icon20 = QIcon()
        icon20.addFile(u":/images/icons/Section.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCrear_Seccion.setIcon(icon20)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.Show = QPushButton(self.centralwidget)
        self.Show.setObjectName(u"Show")
        self.Show.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Show.sizePolicy().hasHeightForWidth())
        self.Show.setSizePolicy(sizePolicy)
        font = QFont()
        font.setBold(False)
        font.setKerning(True)
        self.Show.setFont(font)
        self.Show.setAutoFillBackground(False)
        self.Show.setStyleSheet(u"")
        self.Show.setText(u">>")
        self.Show.setCheckable(False)
        self.Show.setAutoRepeat(False)
        self.Show.setAutoExclusive(False)
        self.Show.setAutoDefault(False)
        self.Show.setFlat(False)

        self.horizontalLayout.addWidget(self.Show)

        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.menu = QScrollArea(self.splitter)
        self.menu.setObjectName(u"menu")
        self.menu.setMinimumSize(QSize(200, 0))
        self.menu.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 198, 460))
        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.menu.setWidget(self.scrollAreaWidgetContents)
        self.splitter.addWidget(self.menu)
        self.board = QFrame(self.splitter)
        self.board.setObjectName(u"board")
        self.board.setMinimumSize(QSize(500, 0))
        self.board.setFrameShape(QFrame.Shape.StyledPanel)
        self.board.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.board)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.graphicsView = BoardView(self.board)
        self.graphicsView.setObjectName(u"graphicsView")

        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)

        self.splitter.addWidget(self.board)

        self.horizontalLayout.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 974, 22))
        self.menubar.setAutoFillBackground(False)
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menuEditar = QMenu(self.menubar)
        self.menuEditar.setObjectName(u"menuEditar")
        self.menuAyuda = QMenu(self.menubar)
        self.menuAyuda.setObjectName(u"menuAyuda")
        self.menuMod = QMenu(self.menubar)
        self.menuMod.setObjectName(u"menuMod")
        self.menuWidgets = QMenu(self.menubar)
        self.menuWidgets.setObjectName(u"menuWidgets")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuWidgets.menuAction())
        self.menubar.addAction(self.menuMod.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionRecientes)
        self.menuArchivo.addAction(self.actionCerrar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExportar)
        self.menuArchivo.addAction(self.actionImprimir)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSobre_Nosotros)
        self.menuArchivo.addAction(self.actionConfiguracion)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addAction(self.actionCortar)
        self.menuAyuda.addAction(self.actionTutorial)
        self.menuAyuda.addAction(self.actionSobre_Nosotros_2)
        self.menuMod.addAction(self.actionCargar_Tema)
        self.menuMod.addAction(self.actionResetear_Tema)
        self.menuMod.addSeparator()
        self.menuMod.addAction(self.actionCargar_UI)
        self.menuMod.addAction(self.actionResetear_UI)
        self.menuWidgets.addAction(self.actionCargar_CI)
        self.menuWidgets.addAction(self.actionGuardar_CI)
        self.menuWidgets.addSeparator()
        self.menuWidgets.addAction(self.actionCrear_Seccion)

        self.retranslateUi(MainWindow)

        self.Show.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNuevo.setText(QCoreApplication.translate("MainWindow", u"Nuevo", None))
#if QT_CONFIG(shortcut)
        self.actionNuevo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar_Como.setText(QCoreApplication.translate("MainWindow", u"Guardar Como", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar_Como.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSobre_Nosotros.setText(QCoreApplication.translate("MainWindow", u"Sobre Nosotros", None))
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionCerrar.setText(QCoreApplication.translate("MainWindow", u"Cerrar", None))
        self.actionSalir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.actionConfiguracion.setText(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n", None))
        self.actionExportar.setText(QCoreApplication.translate("MainWindow", u"Exportar", None))
        self.actionImprimir.setText(QCoreApplication.translate("MainWindow", u"Imprimir", None))
#if QT_CONFIG(shortcut)
        self.actionImprimir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionRecientes.setText(QCoreApplication.translate("MainWindow", u"Recientes", None))
        self.actionCopiar.setText(QCoreApplication.translate("MainWindow", u"Copiar", None))
#if QT_CONFIG(shortcut)
        self.actionCopiar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPegar.setText(QCoreApplication.translate("MainWindow", u"Pegar", None))
#if QT_CONFIG(shortcut)
        self.actionPegar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionCortar.setText(QCoreApplication.translate("MainWindow", u"Cortar", None))
#if QT_CONFIG(shortcut)
        self.actionCortar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionTutorial.setText(QCoreApplication.translate("MainWindow", u"Tutorial", None))
        self.actionSobre_Nosotros_2.setText(QCoreApplication.translate("MainWindow", u"Sobre Nosotros", None))
#if QT_CONFIG(shortcut)
        self.actionSobre_Nosotros_2.setShortcut(QCoreApplication.translate("MainWindow", u"F12", None))
#endif // QT_CONFIG(shortcut)
        self.actionCargar_Tema.setText(QCoreApplication.translate("MainWindow", u"Cargar Tema", None))
        self.actionResetear_Tema.setText(QCoreApplication.translate("MainWindow", u"Resetear Tema", None))
        self.actionCargar_UI.setText(QCoreApplication.translate("MainWindow", u"Cargar UI", None))
        self.actionResetear_UI.setText(QCoreApplication.translate("MainWindow", u"Resetear UI", None))
        self.actionCargar_CI.setText(QCoreApplication.translate("MainWindow", u"Cargar CI", None))
        self.actionGuardar_CI.setText(QCoreApplication.translate("MainWindow", u"Crear CI", None))
        self.actionCrear_Seccion.setText(QCoreApplication.translate("MainWindow", u"Crear Seccion", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
        self.menuEditar.setTitle(QCoreApplication.translate("MainWindow", u"Editar", None))
        self.menuAyuda.setTitle(QCoreApplication.translate("MainWindow", u"Ayuda", None))
        self.menuMod.setTitle(QCoreApplication.translate("MainWindow", u"Mod", None))
        self.menuWidgets.setTitle(QCoreApplication.translate("MainWindow", u"Widgets", None))
    # retranslateUi

